telegram:
  bot:
    name: rpg_cashbot

server:
  port: ${PORT}

changelog:
  path: /changelog/cashbot.xml

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  pattern:
    console: "%clr(%5p) - %msg%n"
  level: info