telegram:
  bot:
    name: rpg_cashbot

server:
  port: ${PORT}

changelog:
  path: /changelog/cashbot.xml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cashbot
    username: pguser
    password: pguser
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
